version: '3.1'
services:
  mongodb:
    image: "mvertes/alpine-mongo"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  postgres:
    image: "postgres:9.2-alpine"
    # restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: sarlacc
      POSTGRES_USER: user

  smtpd:
    build: ./smtpd
    ports:
      - "2500:2500"

  web:
    build: ./web
    ports:
      - "5000:5000"

volumes:
  mongodb:
  postgres:

